name: MLOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout Code ---
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Setup Python (for testing + ML) ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      # --- Lint & Test ---
      - name: Lint code
        run: flake8 .

      - name: Run tests
        run: pytest -q

      # --- Build Docker Image for Model API ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push FastAPI image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/fraud-api:latest
          docker build -t $IMAGE_NAME ./serving
          docker push $IMAGE_NAME

      # --- Deploy to Kubernetes ---
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.28.0"

      - name: Configure Kubeconfig (k3d or minikube)
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/fraud-api
