apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud-container
          image: mydockerhubuser/myproject:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-service
spec:
  selector:
    app: fraud
  ports:
    - port: 80
      targetPort: 8000
  type: NodePort
